<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'SSilence\\ImapClient\\' => array($vendorDir . '/ssilence/php-imap-client/ImapClient'),
);
