<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitaee4f2236d8b9b648551c661873e0835
{
    public static $prefixLengthsPsr4 = array (
        'H' => 
        array (
            'Hackzilla\\PasswordGenerator\\' => 28,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Hackzilla\\PasswordGenerator\\' => 
        array (
            0 => __DIR__ . '/..' . '/hackzilla/password-generator',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitaee4f2236d8b9b648551c661873e0835::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitaee4f2236d8b9b648551c661873e0835::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
